queue: "Hosted VS2017"
variables: 
  BuildConfiguration: Release
steps:
- task: BatchScript@1
  inputs:
    filename: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
    arguments: -no_logo
    modifyEnvironment: true
  displayName: Setup Environment Variables

- task: NuGetToolInstaller@0
  displayName: Use NuGet 4.7
  inputs:
    versionSpec: 4.7.0

- powershell: |    
    mkdir $(Build.ArtifactStagingDirectory)\Logs 

    msbuild .\NuGetKeyVaultSignTool\NuGetKeyVaultSignTool.csproj /restore /t:Pack /p:Configuration=$(BuildConfiguration) /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)\Artifacts /bl:$(Build.ArtifactStagingDirectory)\Logs\build.binlog
        
  displayName: Build
  
    
- task: PowerShell@2
  displayName: Authenticode Sign artifacts
  inputs:
    filePath: Scripts/Sign-Package.ps1
  env:
    SignClientUser: $(SignClientUser)
    SignClientSecret: $(SignClientSecret)
    ArtifactDirectory: $(Build.ArtifactStagingDirectory)\Artifacts

- task: PublishBuildArtifacts@1
  displayName: Publish Build Artifacts
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)\Artifacts
    artifactType: container
    artifactName: Artifacts
  condition: always()


- task: PublishBuildArtifacts@1
  displayName: Publish Log Artifacts
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)\Logs
    artifactType: container
    artifactName: Logs
  condition: always()
